config/routes.rb
Wun::Application.routes.draw do
  devise_for :users, path_names: { sign_up: 'register', sign_in: 'login', sign_out: 'logout' }

  resources :lists, except: [:new] do
  	collection { post :sort }
  end

  resources :items, only: [:index, :edit, :create, :update, :destroy] do
  	collection do
  		post :sort, :complete
  		get :autocomplete_item_name
  	end
  end

  get "pages/home"
  root :to => 'pages#home'
end

app/models/item.rb
class Item < ActiveRecord::Base

  attr_accessible \
    :complete,
    :date_due,
    :date_remind,
    :description,
    :name,
    :star,
    :address,
    :latitude,
    :longitude,
    :image

  belongs_to :list
  belongs_to :user

  validates :name, uniqueness: { case_sensitive: false },
                   presence:   true
  validates :list_id, presence: true

  after_validation :geocode, :if => :address_changed?

  scope :order_position, -> { order(:position) }
  scope :by_user, ->(user) { where(list_id: user.lists) }
  scope :week, -> { where("date_due >= :begin_date AND date_due <= :end_date",
        {begin_date: DateTime.now.beginning_of_week, end_date: DateTime.now.end_of_week}) }

  acts_as_list scope: :list
  paginates_per 10
  geocoded_by :address
  mount_uploader :image, ImageUploader

  searchable do
    text :name, :description
    integer :user_id
  end

  def user
    list.user if list
  end

  def user_id
    list.user_id if list
  end
end

app/models/list.rb
class List < ActiveRecord::Base

  MARKED = 1
  WEEK = 2
  INPUT = 3

  attr_accessible :title

  belongs_to :user
  has_many :items

  validates :title, presence: true, length: { maximum: 200 }
  validates :user_id, presence: true

	scope :order_position, -> { order(:position) }

  acts_as_list

  def items_for_show current_user
    if is_marked?
      Item.by_user(current_user).where(star: true)
    elsif is_week?
      Item.by_user(current_user).week
    else
  	  items.order_position
    end
  end

  def items_count current_user
    items_for_show(current_user).count
  end

  def is_marked?
    self.tag == MARKED
  end

  def is_week?
    self.tag == WEEK
  end

  def is_usual?
    self.tag == nil
  end

  def marked
    self.tag = MARKED
  end

  def week
    self.tag = WEEK
  end

  def input
    self.tag = INPUT
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible \
  	:email,
  	:password,
  	:password_confirmation,
  	:remember_me,
  	:name

  has_many :lists, dependent: :destroy
  has_many :items, through: :lists

	validates :email, uniqueness: { case_sensitive: false },
										presence:   true
  validates :password, presence: true,
  										 length:   { within: 6..30 }

  after_create :create_default_lists

  protected
  def create_default_lists
    titles = ['input', 'marked', 'week', 'private', 'buy', 'films', 'work', 'wish list']
    titles.each do |title|
      default_list = lists.new(title: title)
      case title
        when 'input'
          default_list.input
        when 'week'
          default_list.week
        when 'marked'
          default_list.marked
      end
      default_list.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < LoginController
  autocomplete :item, :name

  before_filter :get_lists, only: [:index, :edit]
  before_filter :find_item_and_list, only: [:edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to lists_path
  end

  def get_autocomplete_items params
    super(params).by_user current_user
  end

  def index
    @items = Item.search do
      fulltext params[:search]
      with(:user_id, current_user.id)
      paginate page: params[:page],  per_page: 10
    end.results

    render layout: 'list'
  end

  def edit
    @items = @list.items.order_position.page params[:page]
  end

  def create
    @list = List.find params[:list]

    params[:star] ||= false
    @item = @list.items.new(name: params[:name], date_due: params[:date_due], star: params[:star])
    check_for_marked_list @list, @item

    notice = @item.save ? 'Item was successfully created.' : ''
    redirect_to @list, notice: notice
  end

  def update
    if @item.update_attributes(params[:item])
      redirect_to @list, notice: 'Item was successfully updated.'
    else
      redirect_to edit_item_path
    end
  end

  def destroy
    @item.destroy

    redirect_to @list
  end

  def sort
    update_position params[:item]
    render nothing: true
  end

  def complete
    update_complete_item params[:id], params[:complete]
    render nothing: true
  end

private
  def get_lists
    @lists = current_user.lists.order_position
  end

  def find_item_and_list
    @item = current_user.items.find params[:id]
    @list = @item.list
  end

  def update_position position_list
    position_list.each_with_index do |id, index|
      Item.update_all({position: index+1}, {id: id})
    end
  end

  def check_for_marked_list list, item
    if list.is_marked?
      item.list = current_user.lists.find_by_tag 3
      item.star = true
    end
  end

  def update_complete_item id, complete_str
    Item.update_all({complete: complete_str == 'true'}, {id: id})
  end
end

app/controllers/lists_controller.rb
class ListsController < LoginController
  layout "list"

  before_filter :get_lists_and_items, only: [:show, :edit]
  before_filter :find_list, only: [:update, :destroy]

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to lists_path
  end

  def index
    @lists = current_user.lists.order_position
  end

  def show
  end

  def edit
  end

  def create
    @list = current_user.lists.new title: params[:title]

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      flash[:error] = "Name is required"
      redirect_to lists_url
    end
  end

  def update
    if @list.update_attributes params[:list]
      redirect_to @list, notice: 'List was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_url
  end

  def sort
    update_position params[:list]
    render nothing: true
  end

private
  def find_list
    @list = current_user.lists.find(params[:id]).decorate
  end

  def get_lists_and_items
    find_list
    @lists = current_user.lists.order_position
    @items = @list.items_for_show(current_user).page params[:page]
  end

  def update_position position_list
    position_list.each_with_index do |id, index|
      List.update_all({position: index+1}, {id: id})
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	before_filter :login_check

private
  def login_check
  	unless current_user
  		redirect_to root_url
  	end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_avatar_url
    'https://assets.github.com/images/gravatars/gravatar-140.png'
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def get_item_row_class_name item_id, current_item_id
		(item_id == current_item_id) ? "info" : "list"
  end
end

app/helpers/lists_helper.rb
module ListsHelper
  def get_list_row_class_name is_current
		is_current ? "info" : "list"
  end
end

app/views/items/_description.html.erb
<% if item.complete %>
  Description:
  <%= item.description.html_safe %>
<% else %>
  <div class="field">
    <%= f.text_area :description, class: "tinymce", rows: 15 %>
  </div>
  <%= tinymce %>
<% end %>

app/views/items/_form.html.erb
<%= form_for item do |f| %>

  <div class="field">
    Done:
    <%= f.check_box :complete %>
    <%= f.text_field :name, maxlength: 255, disabled: item.complete %>
    Star:
    <%= f.check_box :star, disabled: item.complete %>
  </div>

  <div class="field">
    Deadline:
    <%= f.text_field :date_due, class: "calendar", disabled: item.complete, maxlength: 10 %>
  </div>

  <div class="field">
    Date remind:
    <%= f.text_field :date_remind, class: "calendar", disabled: item.complete, maxlength: 10 %>
  </div>

  <%= render 'description', item: item, f: f %>

  <%= render 'location', item: item, f: f %>

  <div class="field">
    Image:
    <%= f.file_field :image, disabled: item.complete %>
  </div>
  <div>
    <%= link_to (image_tag item.image_url(:thumb)), item.image_url, :class => "fancybox" if item.image? %>
  </div>

  <div class="form-actions">
    <%= f.submit 'Update', :class => 'btn btn-primary' %>
    <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
    <%= link_to 'Close', list, :class => 'btn' %>
  </div>
<% end %>

app/views/items/_location.html.erb
<div class="field">
  Location:
  <%= f.text_field :address, disabled: item.complete %>
</div>

<% if item.address? %>
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{item.latitude}%2C#{item.longitude}" %>
<% end %>

app/views/items/edit.html.erb
<div class="container-fluid">
  <%= render 'shared/messages' %>
  <div class="row-fluid">
    <div class="span4">
			<%= render 'shared/list_table', lists: @lists, current_list_id: @list.id %>
    </div>
    <div class="span4">
      <%= render 'shared/item_table', items: @items, current_item_id: @item.id %>
    </div>
    <div class="span4">
    	<%= render 'form', item: @item, list: @list %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<% content_for :lists do %>
  <%= render 'shared/list_table', lists: @lists %>
<% end %>

<% content_for :items do %>
  <%= render 'shared/item_table', items: @items %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wunderlist</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "autocomplete-rails.js" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'shared/navbar' %>

	<%= yield %>

</body>
</html>

app/views/layouts/list.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wunderlist</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "autocomplete-rails.js" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'shared/navbar' %>

  <%= render 'shared/search' %>

  <div class="container-fluid">
    <%= render 'shared/messages' %>
    <div class="row-fluid">
      <div class="span4">
        <%= yield :lists %>
      </div>
      <div class="span8">
      	<%= yield :items %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/lists/_create.html.erb
<%= form_tag lists_path, method: "post" do %>
  <%= text_field_tag :title, params[:title] %>
  <%= submit_tag "New list" , name: nil %>
<% end %>

app/views/lists/edit.html.erb
<% content_for :lists do %>
	<table class="table table-striped">
	<% @lists.each do |list| %>
		<%= @list.list_row list %>
	<% end %>
	</table>
<% end %>

<% content_for :items do %>
  <%= render 'shared/create_items', list: @list %>
  <%= render 'shared/item_table', items: @items %>
<% end %>

app/views/lists/index.html.erb
<% content_for :lists do %>
	<%= render 'shared/list_table', lists: @lists %>
  <br />
  <%= render 'shared/create_lists' %>
<% end %>

app/views/lists/show.html.erb
<% content_for :lists do %>
  <%= render 'shared/list_table', lists: @lists, current_list_id: @list.id %>
  <br />
  <%= render 'shared/create_lists' %>
  <%= @list.destroy_link %>
<% end %>

<% content_for :items do %>
  <%= render 'shared/create_items', list: @list %>
  <%= render 'shared/item_table', items: @items %>
<% end %>

app/views/pages/home.html.erb
<div class="container">
	<% if user_signed_in? %>
		<%= link_to "Start Your Work", lists_path, class: "btn btn-large btn-info" %>
	<% else %>
		<h1>Welcome to Wunderlist!</h1>
	<% end %>
</div>

app/views/shared/_create_items.html.erb
<% unless list.is_week? %>
	<%= form_tag items_path, method: "post" do %>
		<%= hidden_field_tag :list, list.id %>
		<%= text_field_tag :name, nil, maxlength: 255 %>
		Deadline:
		<%= text_field_tag :date_due, nil, class: 'calendar', maxlength: 10 %>
		Star:
		<%= check_box_tag :star %>
		<%= submit_tag "New Item" , name: nil, class: 'btn btn-primary' %>
	<% end %>
<% end %>

app/views/shared/_create_lists.html.erb
<div class="form-actions">
	Add List:
	<%= form_tag lists_path, method: "post" do %>
	  <%= text_field_tag :title, params[:title], maxlength: 255 %>
	<% end %>
</div>

app/views/shared/_item_table.html.erb
<% current_item_id ||= nil %>
<table id="items" data-update-url="<%= sort_items_url %>" data-complete-url="<%= complete_items_url %>" class="table table-striped">
<% items.each do |item| %>
	<%= content_tag_for :tr, item, :class => get_item_row_class_name(item.id, current_item_id) do %>
		<td><%= check_box_tag item.id, "yes", item.complete, class: "complete" %></td>
    <td><%= link_to item.name, edit_item_path(item) %></td>
    <td><%= item.date_due %></td>
    <td><%= "Star" if item.star %></td>
  <% end %>
<% end %>
</table>

<%= paginate items %>

app/views/shared/_list_row.html.erb
<% is_current ||= false %>
<%= content_tag_for :tr, list, :class => get_list_row_class_name(is_current) do %>
  <td><%= link_to list.title, list %></td>
  <td><%= list.items_count current_user %></td>
  <td>
  	<% if list.is_usual? %>
  		<%= link_to 'Edit', edit_list_path(list) %>
  	<% end %>
  </td>
<% end %>

app/views/shared/_list_table.html.erb
<% current_list_id ||= nil %>
<table id="lists" data-update-url="<%= sort_lists_url %>" class="table table-striped">
	<% lists.each do |list| %>
	  <%= render 'shared/list_row', list: list, is_current: list.id == current_list_id %>
	<% end %>
</table>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
  	<button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      </a>
      <%= link_to "Wunderlist", lists_path, class: "brand" %>
      <div class="nav-collapse">
        <%= render 'shared/user_links' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="form-actions">
	<%= form_tag items_path, method: :get do %>
	  <p>
	    <%= autocomplete_field_tag :search, params[:search], autocomplete_item_name_items_path %>
	    <%= submit_tag "Search", name: nil, class: 'btn btn-primary' %>
	  </p>
	<% end %>
</div>

app/views/shared/_user_links.html.erb
<ul class="nav">
	<% if user_signed_in? %>
	  <li><%= link_to "Profile", edit_user_registration_path%> </li>
	  <li><%= link_to "Logout", destroy_user_session_path, method: :delete%> </li>
	<% else %>
	  <li><%= link_to "Sign Up Now!", new_user_registration_path%> </li>
	  <li><%= link_to "Login", new_user_session_path%> </li>
	<% end %>
</ul>